CREATE TABLE IF NOT EXISTS statements ( id INTEGER PRIMARY KEY AUTOINCREMENT, text TEXT NOT NULL, norm_text TEXT NOT NULL UNIQUE, source_note TEXT, status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'hidden')), trump_votes INTEGER NOT NULL DEFAULT 0, toddler_votes INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT (datetime('now')) );
CREATE INDEX IF NOT EXISTS idx_statements_status ON statements (status);
CREATE TABLE IF NOT EXISTS votes ( statement_id INTEGER NOT NULL REFERENCES statements (id) ON DELETE CASCADE, player_id TEXT NOT NULL, choice TEXT NOT NULL CHECK (choice IN ('trump', 'toddler')), created_at TEXT NOT NULL DEFAULT (datetime('now')), PRIMARY KEY (statement_id, player_id) );
CREATE TABLE IF NOT EXISTS rate_events ( bucket TEXT NOT NULL, created_at INTEGER NOT NULL );
CREATE INDEX IF NOT EXISTS idx_rate_events ON rate_events (bucket, created_at);
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Refuses to wear a coat, no matter how cold it is.', 'refuses to wear a coat, no matter how cold it is', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Insists on pressing the elevator button themselves.', 'insists on pressing the elevator button themselves', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Gets upset when someone else''s tower is taller.', 'gets upset when someone else''s tower is taller', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Everything is either "the best" or "a total disaster".', 'everything is either "the best" or "a total disaster"', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Needs a nap after lunch, but will deny being tired.', 'needs a nap after lunch, but will deny being tired', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Only eats food that is beige.', 'only eats food that is beige', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Talks about themselves in the third person.', 'talks about themselves in the third person', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Has to be the first one through the door.', 'has to be the first one through the door', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Announces the same achievement several times a day.', 'announces the same achievement several times a day', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Should not be left alone with a phone.', 'should not be left alone with a phone', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Gets louder when asked to be quieter.', 'gets louder when asked to be quieter', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Will not admit to knocking over the lamp.', 'will not admit to knocking over the lamp', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Deeply interested in large trucks.', 'deeply interested in large trucks', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Would like a parade.', 'would like a parade', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Has a hairstyle that takes longer than the rest of getting dressed.', 'has a hairstyle that takes longer than the rest of getting dressed', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Gives everyone they meet a nickname.', 'gives everyone they meet a nickname', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Has fallen asleep somewhere they were supposed to be paying attention.', 'has fallen asleep somewhere they were supposed to be paying attention', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Grabs things that belong to other people.', 'grabs things that belong to other people', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Repeats a sentence louder rather than explaining it differently.', 'repeats a sentence louder rather than explaining it differently', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Became an expert on the subject yesterday.', 'became an expert on the subject yesterday', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('“This mine!”', '“this mine!”', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('“I did it. I did it all by myself.”', '“i did it. i did it all by myself.”', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('“I''m not tired!”', '“i''m not tired!”', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('“You''re not my friend anymore.”', '“you''re not my friend anymore.”', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('“He started it.”', '“he started it.”', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('“Mine was bigger.”', '“mine was bigger.”', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('“No! I do it!”', '“no! i do it!”', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('“Watch me. Watch me. Watch me.”', '“watch me. watch me. watch me.”', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('“That''s not fair!”', '“that''s not fair!”', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('“Everybody says I''m the best at this.”', '“everybody says i''m the best at this.”', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Wears diapers.', 'wears diapers', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Has tantrums.', 'has tantrums', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Cannot pronounce your name properly.', 'cannot pronounce your name properly', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Afraid of the vacuum cleaner.', 'afraid of the vacuum cleaner', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Needs help with buttons.', 'needs help with buttons', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Doesn''t like sharing.', 'doesn''t like sharing', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Throws food.', 'throws food', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Requires a specific cup.', 'requires a specific cup', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Gets carried when tired.', 'gets carried when tired', NULL, 'approved');
INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES ('Needs constant supervision.', 'needs constant supervision', NULL, 'approved');
