ALTER TABLE statements ADD COLUMN funny_votes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE statements ADD COLUMN meh_votes INTEGER NOT NULL DEFAULT 0;
ALTER TABLE votes ADD COLUMN decision_ms INTEGER;
ALTER TABLE votes ADD COLUMN rating TEXT;
