#!/usr/bin/env node
/**
 * Import seed/statements.json into D1 as approved statements.
 *
 *   npm run seed           -> the local development database
 *   npm run seed:remote    -> the deployed database
 *
 * Works the same on Windows, macOS and Linux: it writes a .sql file and hands
 * it to wrangler. Re-running is safe -- duplicates are ignored, and statements
 * already in the database keep their votes.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { validateSubmission, normalizeText } from '../src/lib/text.js';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const argv = process.argv.slice(2);

const remote = argv.includes('--remote');
const dryRun = argv.includes('--dry-run');
const seedPath = resolve(root, argv.find((a) => a.startsWith('--file='))?.slice('--file='.length) ?? 'seed/statements.json');

function fail(message) {
  console.error(`\n  ${message}\n`);
  process.exit(1);
}

/* ---------- read the seed file ---------- */

if (!existsSync(seedPath)) fail(`No seed file at ${seedPath}`);

let parsed;
try {
  parsed = JSON.parse(readFileSync(seedPath, 'utf8'));
} catch (err) {
  fail(`${seedPath} is not valid JSON: ${err.message}`);
}

const entries = Array.isArray(parsed) ? parsed : parsed?.statements;
if (!Array.isArray(entries)) {
  fail('Expected the seed file to be {"statements": [...]} or a plain array.');
}

/* ---------- validate, and drop duplicates within the file itself ---------- */

const rows = [];
const seen = new Map();
const problems = [];

entries.forEach((entry, index) => {
  const where = `entry ${index + 1}`;
  const check = validateSubmission({ text: entry?.text, sourceNote: entry?.source_note ?? entry?.sourceNote });
  if (!check.ok) {
    problems.push(`${where}: ${check.error}`);
    return;
  }
  const key = normalizeText(check.value.text);
  if (seen.has(key)) {
    problems.push(`${where}: same as entry ${seen.get(key)}, skipped`);
    return;
  }
  seen.set(key, index + 1);
  rows.push(check.value);
});

if (rows.length === 0) fail('Nothing importable in the seed file.');

/* ---------- build the SQL ---------- */

const quote = (value) => (value === null || value === undefined ? 'NULL' : `'${String(value).replace(/'/g, "''")}'`);

const sql = [
  '-- Generated by scripts/import-seed.mjs. Do not edit; edit seed/statements.json instead.',
  ...rows.map(
    ({ text, sourceNote, normText }) =>
      `INSERT OR IGNORE INTO statements (text, norm_text, source_note, status) VALUES (${quote(text)}, ${quote(normText)}, ${quote(sourceNote)}, 'approved');`,
  ),
  '',
].join('\n');

const outDir = join(root, '.tmp');
mkdirSync(outDir, { recursive: true });
const outFile = join(outDir, 'seed.sql');
writeFileSync(outFile, sql, 'utf8');

console.log(`\n  ${rows.length} statement${rows.length === 1 ? '' : 's'} ready from ${seedPath}`);
for (const problem of problems) console.log(`  skipped — ${problem}`);

if (dryRun) {
  console.log(`\n  --dry-run: SQL written to ${outFile}, nothing imported.\n`);
  process.exit(0);
}

/* ---------- hand it to wrangler ---------- */

const databaseName =
  readFileSync(join(root, 'wrangler.toml'), 'utf8').match(/database_name\s*=\s*"([^"]+)"/)?.[1] ?? 'trump_or_toddler';

const args = ['wrangler', 'd1', 'execute', databaseName, remote ? '--remote' : '--local', '--file', outFile];
console.log(`  running: npx ${args.join(' ')}\n`);

// shell: true so this also finds npx.cmd on Windows.
const result = spawnSync('npx', args, { stdio: 'inherit', shell: true, cwd: root });

if (result.status !== 0) {
  fail(
    'wrangler could not run the import.\n' +
      '  If the database does not exist yet, see "Deploying" in README.md.\n' +
      `  The SQL is still at ${outFile} if you want to run it by hand.`,
  );
}

console.log(`\n  Imported into the ${remote ? 'remote' : 'local'} database.\n`);
